services:
  - type: web
    name: pudu-python-api
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    autoDeploy: true
